/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Summary;
import EDD.HashTable;

/**
 *
 * @author guzzo
 */
public class AnalizeSummary extends javax.swing.JFrame {
    private static Summary summary;
    /**
     * Creates new form AnalizeSummary
     */
    public AnalizeSummary(Summary summary) {        
        initComponents();
        this.summary = summary;
        
        
        TitleOutput.setText(summary.getTitle());
        authorsOutput.setText(summary.getAuthor());
        
        String[] arrayKeywords = summary.getKeywords().split(", ");
        int[] arrayCount = new int[arrayKeywords.length];
        
        for (int i = 0; i < arrayCount.length; i++) {
            arrayCount[i] = 0;
        }
        
        
        String[] arrayBody = summary.getBody().split(" ");
        
        
        for (int i = 0; i < arrayKeywords.length; i++) {
            
            String keyword = arrayKeywords[i];
            for(String word: arrayBody){
                if(word.contains(keyword)){
                    arrayCount[i] = arrayCount[i] + 1;
                }   
            }
        }
        
        String keywords = "";
        for (int i = 0; i < arrayKeywords.length; i++) {
            keywords += arrayKeywords[i] + ": " + arrayCount[i] + "\n";
        }
        
        keywordsOuput.setText(keywords);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleOutput = new javax.swing.JLabel();
        authorsOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keywordsOuput = new javax.swing.JTextArea();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleOutput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitleOutput.setText("Titulo");
        jPanel1.add(TitleOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        authorsOutput.setText("Autores: ");
        jPanel1.add(authorsOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        keywordsOuput.setColumns(20);
        keywordsOuput.setRows(5);
        keywordsOuput.setEnabled(false);
        jScrollPane1.setViewportView(keywordsOuput);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 470, 120));

        close.setText("Cerrar");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizeSummary(summary).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleOutput;
    private javax.swing.JLabel authorsOutput;
    private javax.swing.JButton close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea keywordsOuput;
    // End of variables declaration//GEN-END:variables
}
