/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.LoadTXT;
import Clases.Summary;
import EDD.HashTable;
import EDD.List;
import javax.swing.JOptionPane;

/**
 *
 * @author guzzo
 */
public class MainMenu extends javax.swing.JFrame {
    private HashTable htTitle;
    private HashTable htKeywords;
    private HashTable htAuthors;
    
    
    public MainMenu() {
        initComponents();
        
        this.htTitle = new HashTable(100);
        this.htKeywords = new HashTable(100);
        this.htAuthors = new HashTable(100);
           
    }
    
    public MainMenu(HashTable htTitle, HashTable htKeywords, HashTable htAuthors) {
        initComponents();
        
        this.htTitle = htTitle;
        this.htKeywords = htKeywords;
        this.htAuthors = htAuthors;
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadSummary = new javax.swing.JButton();
        analyzeSummary = new javax.swing.JButton();
        searchKeyword = new javax.swing.JButton();
        searchAuthor = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadSummary.setText("Cargar Resumen");
        loadSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(loadSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        analyzeSummary.setText("Analizar Resumen");
        analyzeSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(analyzeSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        searchKeyword.setText("Buscar por palabra clave ");
        searchKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeywordActionPerformed(evt);
            }
        });
        jPanel1.add(searchKeyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        searchAuthor.setText("Buscar por autor");
        searchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(searchAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, -1));

        save.setText("Guardar cambios");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSummaryActionPerformed
        Summary summary = LoadTXT.read();
        htTitle.add(summary, 1); //Agregar por titulo
        htKeywords.add(summary, 2); //Agregar por palabras claves
        htAuthors.add(summary, 3); //Agregsar por autores
        
        
        if(summary != null){            
            JOptionPane.showMessageDialog(null, "El resumen fue cargado exitosamente!");            
        }                
    }//GEN-LAST:event_loadSummaryActionPerformed

    private void analyzeSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeSummaryActionPerformed
        SummaryList sl = new SummaryList(htTitle);
        sl.setVisible(true);
    }//GEN-LAST:event_analyzeSummaryActionPerformed

    private void searchKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeywordActionPerformed
        String keyword = JOptionPane.showInputDialog("Ingrese la palabra clave");
            
        Summary summary = htKeywords.get(keyword);
        if(summary == null){
            JOptionPane.showMessageDialog(null, "No se encontro el resumen");
        }
        else{
            AnalizeSummary as = new AnalizeSummary(summary); 
            as.setVisible(true);            
        }
    }//GEN-LAST:event_searchKeywordActionPerformed

    private void searchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorActionPerformed
        String author = JOptionPane.showInputDialog("Ingrese el autor");
            
        Summary summary = htAuthors.get(author);
        if(summary == null){
            JOptionPane.showMessageDialog(null, "No se encontro el resumen");
        }
        else{
            AnalizeSummary as = new AnalizeSummary(summary); 
            as.setVisible(true);            
        }
    }//GEN-LAST:event_searchAuthorActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        LoadTXT.save(htTitle);
        JOptionPane.showMessageDialog(null, "Se han guardado los cambios!");
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeSummary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadSummary;
    private javax.swing.JButton save;
    private javax.swing.JButton searchAuthor;
    private javax.swing.JButton searchKeyword;
    // End of variables declaration//GEN-END:variables
}
